// ===== Career Intelligence Knowledge Base =====
import type { UniqueCourse, Institution, Internship, GovtCourse, ShortCourse } from '@/types';

// ===== Country List =====
export const countries = [
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'AE', name: 'UAE', flag: '🇦🇪' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱' },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪' },
];

// ===== Entrance Exams =====
export const entranceExams = {
  engineering: [
    { name: 'JEE Main', fullForm: 'Joint Entrance Examination Main', conductingBody: 'NTA', frequency: 'Twice a year', eligibility: 'Class 12 PCM', website: 'jeemain.nta.nic.in' },
    { name: 'JEE Advanced', fullForm: 'Joint Entrance Examination Advanced', conductingBody: 'IITs (rotational)', frequency: 'Once a year', eligibility: 'JEE Main qualifiers', website: 'jeeadv.ac.in' },
    { name: 'BITSAT', fullForm: 'Birla Institute of Technology and Science Admission Test', conductingBody: 'BITS Pilani', frequency: 'Twice a year', eligibility: 'Class 12 PCM', website: 'bitsadmission.com' },
    { name: 'VITEEE', fullForm: 'VIT Engineering Entrance Exam', conductingBody: 'VIT University', frequency: 'Once a year', eligibility: 'Class 12 PCM', website: 'vit.ac.in' },
    { name: 'SRMJEEE', fullForm: 'SRM Joint Engineering Entrance Exam', conductingBody: 'SRM University', frequency: 'Once a year', eligibility: 'Class 12 PCM', website: 'srmist.edu.in' },
    { name: 'COMEDK', fullForm: 'Consortium of Medical, Engineering and Dental Colleges of Karnataka', conductingBody: 'COMEDK', frequency: 'Once a year', eligibility: 'Class 12 PCM', website: 'comedk.org' },
    { name: 'WBJEE', fullForm: 'West Bengal Joint Entrance Exam', conductingBody: 'WBJEEB', frequency: 'Once a year', eligibility: 'Class 12 PCM', website: 'wbjeeb.nic.in' },
    { name: 'MHT CET', fullForm: 'Maharashtra Common Entrance Test', conductingBody: 'State CET Cell, Maharashtra', frequency: 'Once a year', eligibility: 'Class 12 PCM', website: 'cetcell.mahacet.org' },
  ],
  medical: [
    { name: 'NEET UG', fullForm: 'National Eligibility cum Entrance Test (Undergraduate)', conductingBody: 'NTA', frequency: 'Once a year', eligibility: 'Class 12 PCB', website: 'neet.nta.nic.in' },
    { name: 'AIIMS Nursing', fullForm: 'AIIMS Nursing Entrance Exam', conductingBody: 'AIIMS', frequency: 'Once a year', eligibility: 'Class 12 PCB', website: 'aiimsexams.ac.in' },
    { name: 'JIPMER', fullForm: 'Jawaharlal Institute PG Medical Exam', conductingBody: 'JIPMER', frequency: 'Once a year', eligibility: 'NEET qualified', website: 'jipmer.edu.in' },
  ],
  management: [
    { name: 'CAT', fullForm: 'Common Admission Test', conductingBody: 'IIMs (rotational)', frequency: 'Once a year', eligibility: 'Graduation (50%)', website: 'iimcat.ac.in' },
    { name: 'XAT', fullForm: 'Xavier Aptitude Test', conductingBody: 'XLRI Jamshedpur', frequency: 'Once a year', eligibility: 'Graduation', website: 'xatonline.in' },
    { name: 'MAT', fullForm: 'Management Aptitude Test', conductingBody: 'AIMA', frequency: '4 times a year', eligibility: 'Graduation', website: 'mat.aima.in' },
    { name: 'CMAT', fullForm: 'Common Management Admission Test', conductingBody: 'NTA', frequency: 'Once a year', eligibility: 'Graduation', website: 'cmat.nta.nic.in' },
    { name: 'SNAP', fullForm: 'Symbiosis National Aptitude Test', conductingBody: 'Symbiosis International University', frequency: 'Once a year', eligibility: 'Graduation', website: 'snaptest.org' },
    { name: 'NMAT', fullForm: 'NMIMS Management Aptitude Test', conductingBody: 'GMAC', frequency: 'Once a year', eligibility: 'Graduation (50%)', website: 'nmat.org.in' },
  ],
  law: [
    { name: 'CLAT', fullForm: 'Common Law Admission Test', conductingBody: 'Consortium of NLUs', frequency: 'Once a year', eligibility: 'Class 12 (UG) / Graduation (PG)', website: 'consortiumofnlus.ac.in' },
    { name: 'AILET', fullForm: 'All India Law Entrance Test', conductingBody: 'NLU Delhi', frequency: 'Once a year', eligibility: 'Class 12 (UG) / Graduation (PG)', website: 'nludelhi.ac.in' },
    { name: 'LSAT India', fullForm: 'Law School Admission Test India', conductingBody: 'LSAC', frequency: 'Once a year', eligibility: 'Class 12 (UG) / Graduation (PG)', website: 'lsat.org.in' },
  ],
  design: [
    { name: 'NID DAT', fullForm: 'National Institute of Design Design Aptitude Test', conductingBody: 'NID', frequency: 'Once a year', eligibility: 'Class 12 / Graduation', website: 'admissions.nid.edu' },
    { name: 'UCEED', fullForm: 'Undergraduate Common Entrance Exam for Design', conductingBody: 'IIT Bombay', frequency: 'Once a year', eligibility: 'Class 12', website: 'uceed.iitb.ac.in' },
    { name: 'CEED', fullForm: 'Common Entrance Exam for Design', conductingBody: 'IIT Bombay', frequency: 'Once a year', eligibility: 'Graduation', website: 'ceed.iitb.ac.in' },
    { name: 'NIFT Entrance', fullForm: 'National Institute of Fashion Technology Entrance', conductingBody: 'NIFT', frequency: 'Once a year', eligibility: 'Class 12', website: 'nift.ac.in' },
  ],
  civilServices: [
    { name: 'UPSC CSE', fullForm: 'Union Public Service Commission Civil Services Examination', conductingBody: 'UPSC', frequency: 'Once a year', eligibility: 'Graduation', website: 'upsc.gov.in' },
    { name: 'UPSC CDS', fullForm: 'Combined Defence Services Examination', conductingBody: 'UPSC', frequency: 'Twice a year', eligibility: 'Graduation', website: 'upsc.gov.in' },
    { name: 'SSC CGL', fullForm: 'Staff Selection Commission Combined Graduate Level', conductingBody: 'SSC', frequency: 'Once a year', eligibility: 'Graduation', website: 'ssc.nic.in' },
    { name: 'State PSC', fullForm: 'State Public Service Commission Exams', conductingBody: 'State PSCs', frequency: 'Varies', eligibility: 'Graduation', website: 'varies' },
  ],
  general: [
    { name: 'GATE', fullForm: 'Graduate Aptitude Test in Engineering', conductingBody: 'IISc/IITs', frequency: 'Once a year', eligibility: 'B.E./B.Tech/M.Sc', website: 'gate.iitk.ac.in' },
    { name: 'GRE', fullForm: 'Graduate Record Examination', conductingBody: 'ETS', frequency: 'Multiple times', eligibility: 'Graduation', website: 'ets.org/gre' },
    { name: 'GMAT', fullForm: 'Graduate Management Admission Test', conductingBody: 'GMAC', frequency: 'Multiple times', eligibility: 'Graduation', website: 'mba.com' },
    { name: 'IELTS', fullForm: 'International English Language Testing System', conductingBody: 'British Council/IDP', frequency: 'Multiple times', eligibility: 'No minimum', website: 'ielts.org' },
    { name: 'TOEFL', fullForm: 'Test of English as a Foreign Language', conductingBody: 'ETS', frequency: 'Multiple times', eligibility: 'No minimum', website: 'ets.org/toefl' },
  ],
};

export const topInstitutions = {
  engineering: [
    { name: 'IIT Bombay', nirf: 1, avgPackage: '21.7 LPA', location: 'Mumbai', type: 'Government' },
    { name: 'IIT Delhi', nirf: 2, avgPackage: '20.5 LPA', location: 'New Delhi', type: 'Government' },
    { name: 'IIT Madras', nirf: 3, avgPackage: '19.8 LPA', location: 'Chennai', type: 'Government' },
    { name: 'IIT Kanpur', nirf: 4, avgPackage: '18.5 LPA', location: 'Kanpur', type: 'Government' },
    { name: 'IIT Kharagpur', nirf: 5, avgPackage: '18.2 LPA', location: 'Kharagpur', type: 'Government' },
    { name: 'IIT Roorkee', nirf: 6, avgPackage: '17.8 LPA', location: 'Roorkee', type: 'Government' },
    { name: 'NIT Trichy', nirf: 9, avgPackage: '12.5 LPA', location: 'Tiruchirappalli', type: 'Government' },
    { name: 'BITS Pilani', nirf: 11, avgPackage: '16.2 LPA', location: 'Pilani', type: 'Private' },
    { name: 'VIT Vellore', nirf: 12, avgPackage: '8.5 LPA', location: 'Vellore', type: 'Private' },
    { name: 'IIIT Hyderabad', nirf: 14, avgPackage: '22.0 LPA', location: 'Hyderabad', type: 'Government' },
  ],
  management: [
    { name: 'IIM Ahmedabad', nirf: 1, avgPackage: '35.5 LPA', location: 'Ahmedabad', type: 'Government' },
    { name: 'IIM Bangalore', nirf: 2, avgPackage: '33.8 LPA', location: 'Bangalore', type: 'Government' },
    { name: 'IIM Calcutta', nirf: 3, avgPackage: '32.5 LPA', location: 'Kolkata', type: 'Government' },
    { name: 'ISB Hyderabad', nirf: 5, avgPackage: '38.0 LPA', location: 'Hyderabad', type: 'Private' },
    { name: 'XLRI Jamshedpur', nirf: 6, avgPackage: '28.5 LPA', location: 'Jamshedpur', type: 'Private' },
    { name: 'FMS Delhi', nirf: 8, avgPackage: '30.2 LPA', location: 'New Delhi', type: 'Government' },
  ],
  medical: [
    { name: 'AIIMS New Delhi', nirf: 1, avgPackage: 'N/A (Govt)', location: 'New Delhi', type: 'Government' },
    { name: 'PGIMER Chandigarh', nirf: 2, avgPackage: 'N/A (Govt)', location: 'Chandigarh', type: 'Government' },
    { name: 'CMC Vellore', nirf: 3, avgPackage: 'N/A (Govt)', location: 'Vellore', type: 'Private' },
    { name: 'JIPMER Puducherry', nirf: 5, avgPackage: 'N/A (Govt)', location: 'Puducherry', type: 'Government' },
    { name: 'MAMC Delhi', nirf: 8, avgPackage: 'N/A (Govt)', location: 'New Delhi', type: 'Government' },
  ],
};

export const careerFields: Record<string, {
  name: string;
  growthPercent: number;
  demandLevel: 'Very High' | 'High' | 'Medium' | 'Growing';
  salaryRanges: { entry: string; mid: string; senior: string };
  topCompanies: string[];
  keySkills: string[];
  hotRoles: string[];
}> = {
  technology: {
    name: 'Software & IT',
    growthPercent: 25,
    demandLevel: 'Very High',
    salaryRanges: { entry: '4-8 LPA', mid: '10-25 LPA', senior: '30-80 LPA' },
    topCompanies: ['TCS', 'Infosys', 'Wipro', 'Google India', 'Microsoft India', 'Amazon India', 'Flipkart', 'Razorpay'],
    keySkills: ['Programming', 'Cloud Computing', 'DevOps', 'System Design', 'Data Structures'],
    hotRoles: ['Full Stack Developer', 'Backend Engineer', 'Cloud Architect', 'DevOps Engineer', 'Tech Lead'],
  },
  ai_ml: {
    name: 'AI & Machine Learning',
    growthPercent: 35,
    demandLevel: 'Very High',
    salaryRanges: { entry: '6-12 LPA', mid: '15-35 LPA', senior: '40-100 LPA' },
    topCompanies: ['Google DeepMind', 'Microsoft Research', 'Amazon Science', 'Flipkart', 'Swiggy', 'Zomato', 'Jio', 'NVIDIA India'],
    keySkills: ['Python', 'TensorFlow/PyTorch', 'NLP', 'Computer Vision', 'MLOps', 'Statistics'],
    hotRoles: ['ML Engineer', 'Data Scientist', 'AI Researcher', 'NLP Engineer', 'MLOps Engineer'],
  },
  product: {
    name: 'Product Management',
    growthPercent: 30,
    demandLevel: 'High',
    salaryRanges: { entry: '8-15 LPA', mid: '18-35 LPA', senior: '40-70 LPA' },
    topCompanies: ['Flipkart', 'Amazon', 'Razorpay', 'CRED', 'Swiggy', 'Zomato', 'Meesho', 'Groww'],
    keySkills: ['Product Strategy', 'Data Analysis', 'User Research', 'Agile', 'Stakeholder Management'],
    hotRoles: ['Product Manager', 'Associate PM', 'Group PM', 'VP Product', 'Chief Product Officer'],
  },
  design: {
    name: 'UX/UI Design',
    growthPercent: 22,
    demandLevel: 'High',
    salaryRanges: { entry: '4-9 LPA', mid: '10-22 LPA', senior: '25-50 LPA' },
    topCompanies: ['Google India', 'Microsoft', 'Flipkart', 'Swiggy', 'Zomato', 'Razorpay', 'Infosys', 'TCS'],
    keySkills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Interaction Design'],
    hotRoles: ['UX Designer', 'UI Designer', 'Product Designer', 'Design Lead', 'UX Researcher'],
  },
  finance: {
    name: 'Finance & Fintech',
    growthPercent: 20,
    demandLevel: 'High',
    salaryRanges: { entry: '5-10 LPA', mid: '12-28 LPA', senior: '30-60 LPA' },
    topCompanies: ['HDFC Bank', 'ICICI Bank', 'Razorpay', 'PhonePe', 'Paytm', 'Groww', 'Zerodha', 'Goldman Sachs India'],
    keySkills: ['Financial Modeling', 'Risk Analysis', 'SQL', 'Python', 'Regulatory Knowledge'],
    hotRoles: ['Financial Analyst', 'Risk Manager', 'Fintech Engineer', 'Investment Analyst', 'Compliance Officer'],
  },
  healthcare: {
    name: 'Healthcare & Biotech',
    growthPercent: 18,
    demandLevel: 'High',
    salaryRanges: { entry: '5-9 LPA', mid: '10-22 LPA', senior: '25-50 LPA' },
    topCompanies: ['Biocon', 'Dr. Reddys', 'Sun Pharma', 'Cipla', 'Apollo Hospitals', 'Fortis', 'Serum Institute', 'Bharat Biotech'],
    keySkills: ['Clinical Research', 'Biostatistics', 'Regulatory Affairs', 'Lab Techniques', 'Pharmacovigilance'],
    hotRoles: ['Clinical Research Associate', 'Biotech Scientist', 'Medical Writer', 'Regulatory Affairs Specialist', 'Healthcare Consultant'],
  },
};

export const riasecMbtiCombinations: Record<string, {
  title: string;
  description: string;
  careerMatches: string[];
  strengths: string[];
  developmentAreas: string[];
}> = {
  'RI-INTJ': { title: 'The Technical Innovator', description: 'You combine hands-on problem-solving with strategic vision.', careerMatches: ['Mechanical Engineer', 'Systems Architect', 'Robotics Engineer', 'R&D Director'], strengths: ['Deep technical knowledge', 'Strategic planning', 'Independent problem-solving'], developmentAreas: ['Team collaboration', 'Communication skills', 'Adapting to ambiguity'] },
  'IA-INFP': { title: 'The Creative Researcher', description: 'Your investigative curiosity is fueled by deep personal values and creativity.', careerMatches: ['Research Scientist', 'UX Researcher', 'Data Journalist', 'Environmental Scientist'], strengths: ['Deep empathy', 'Creative problem-solving', 'Meaning-driven motivation'], developmentAreas: ['Time management', 'Handling criticism', 'Decision-making under pressure'] },
  'AS-ENFJ': { title: 'The Inspiring Educator', description: 'You combine artistic expression with a desire to help others grow.', careerMatches: ['Art Therapist', 'Creative Director (EdTech)', 'Curriculum Designer', 'Cultural Program Manager'], strengths: ['Inspiring leadership', 'Creative communication', 'Deep empathy'], developmentAreas: ['Setting boundaries', 'Objective decision-making', 'Self-care'] },
  'SE-ESTJ': { title: 'The Business Leader', description: 'Your social intelligence and enterprising drive make you a natural leader.', careerMatches: ['Business Development Head', 'Sales Director', 'HR Director', 'Operations Manager'], strengths: ['People management', 'Goal-oriented execution', 'Organizational skills'], developmentAreas: ['Flexibility', 'Creative thinking', 'Patience with process'] },
  'EC-ISTJ': { title: 'The Corporate Strategist', description: 'You blend enterprising vision with conventional precision.', careerMatches: ['Financial Controller', 'Compliance Manager', 'Operations Head', 'Business Analyst'], strengths: ['Strategic planning', 'Attention to detail', 'Reliability'], developmentAreas: ['Adaptability', 'Innovation', 'Emotional intelligence'] },
  'IC-INTP': { title: 'The Analytical Architect', description: 'Your investigative depth and conventional precision make you exceptional at designing complex systems.', careerMatches: ['Data Architect', 'Software Architect', 'Quantitative Analyst', 'Research Engineer'], strengths: ['Logical analysis', 'Pattern recognition', 'System design'], developmentAreas: ['Communication', 'Time management', 'Collaboration'] },
  'AE-ENTP': { title: 'The Creative Entrepreneur', description: 'Your artistic vision paired with enterprising drive makes you a startup founder at heart.', careerMatches: ['Startup Founder', 'Creative Agency Owner', 'Product Innovator', 'Venture Capital Analyst'], strengths: ['Innovation', 'Persuasion', 'Visionary thinking'], developmentAreas: ['Follow-through', 'Financial planning', 'Attention to detail'] },
  'SI-INFJ': { title: 'The Insightful Healer', description: 'Your social nature combined with investigative depth allows you to deeply understand and help people.', careerMatches: ['Clinical Psychologist', 'Counselor', 'Social Worker', 'Healthcare Administrator'], strengths: ['Deep understanding of people', 'Insightful analysis', 'Compassionate service'], developmentAreas: ['Self-advocacy', 'Setting boundaries', 'Handling conflict'] },
  'RE-ESTP': { title: 'The Action Executive', description: 'You combine hands-on capability with enterprising energy.', careerMatches: ['Sales Engineer', 'Operations Executive', 'Project Manager', 'Entrepreneur'], strengths: ['Quick decision-making', 'Hands-on execution', 'Adaptability'], developmentAreas: ['Long-term planning', 'Patience', 'Delegation'] },
  'AC-ISFP': { title: 'The Precision Artist', description: 'Your artistic sensibility meets conventional detail-orientation.', careerMatches: ['Graphic Designer', 'Architect', 'Fashion Designer', 'Interior Designer'], strengths: ['Aesthetic sense', 'Attention to detail', 'Craftsmanship'], developmentAreas: ['Self-promotion', 'Handling criticism', 'Networking'] },
  'IE-ENTJ': { title: 'The Research Executive', description: 'Your investigative mind and enterprising ambition drive you to lead research-driven organizations.', careerMatches: ['Chief Technology Officer', 'R&D Director', 'Strategy Consultant', 'Biotech CEO'], strengths: ['Strategic vision', 'Analytical depth', 'Leadership'], developmentAreas: ['Patience with process', 'Emotional intelligence', 'Work-life balance'] },
  'SC-ESFJ': { title: 'The Community Organizer', description: 'Your social warmth and conventional reliability make you the backbone of any community.', careerMatches: ['School Administrator', 'Healthcare Manager', 'Community Program Director', 'Event Manager'], strengths: ['People skills', 'Organization', 'Reliability'], developmentAreas: ['Innovation', 'Handling change', 'Delegation'] },
  'RA-ISTP': { title: 'The Practical Creator', description: 'You blend hands-on skill with artistic vision.', careerMatches: ['Industrial Designer', 'Mechanical Designer', 'Product Engineer', 'Artisan Entrepreneur'], strengths: ['Hands-on skill', 'Creative problem-solving', 'Independence'], developmentAreas: ['Communication', 'Team collaboration', 'Planning'] },
  'IS-ISTJ': { title: 'The Methodical Researcher', description: 'Your investigative nature is grounded by systematic, reliable methods.', careerMatches: ['Lab Researcher', 'Quality Analyst', 'Forensic Scientist', 'Academic Researcher'], strengths: ['Methodical approach', 'Thoroughness', 'Reliability'], developmentAreas: ['Speed', 'Creative thinking', 'Adaptability'] },
  'EA-ENFP': { title: 'The Visionary Leader', description: 'Your enterprising energy and artistic creativity make you a charismatic leader who inspires through vision.', careerMatches: ['Creative Director', 'Marketing Director', 'Startup CEO', 'Brand Strategist'], strengths: ['Vision', 'Charisma', 'Creative problem-solving'], developmentAreas: ['Focus', 'Detail management', 'Follow-through'] },
  'RC-ESTJ': { title: 'The Systems Manager', description: 'Your practical skills and conventional mindset make you exceptional at managing complex systems.', careerMatches: ['Operations Manager', 'Supply Chain Director', 'Factory Manager', 'Quality Head'], strengths: ['Systems thinking', 'Reliability', 'Efficiency'], developmentAreas: ['Innovation', 'Flexibility', 'People management'] },
};

export const inDemandSkills = [
  { name: 'Artificial Intelligence & ML', demand: 95, trend: 'up' as const, category: 'Tech' },
  { name: 'Cloud Computing (AWS/Azure/GCP)', demand: 92, trend: 'up' as const, category: 'Tech' },
  { name: 'Full Stack Development', demand: 90, trend: 'stable' as const, category: 'Tech' },
  { name: 'Data Science & Analytics', demand: 88, trend: 'up' as const, category: 'Tech' },
  { name: 'Cybersecurity', demand: 87, trend: 'up' as const, category: 'Tech' },
  { name: 'Product Management', demand: 85, trend: 'up' as const, category: 'Business' },
  { name: 'UX/UI Design', demand: 82, trend: 'up' as const, category: 'Design' },
  { name: 'DevOps & SRE', demand: 80, trend: 'up' as const, category: 'Tech' },
  { name: 'Blockchain & Web3', demand: 72, trend: 'up' as const, category: 'Tech' },
  { name: 'Digital Marketing', demand: 78, trend: 'stable' as const, category: 'Business' },
  { name: 'Financial Modeling', demand: 75, trend: 'stable' as const, category: 'Finance' },
  { name: 'Communication & Soft Skills', demand: 85, trend: 'up' as const, category: 'Soft Skills' },
];

export const learningPlatforms = [
  { name: 'Coursera', description: 'University courses from IITs, IIITs & global partners', url: 'coursera.org', focus: ['All fields'], indianContent: true, free: true },
  { name: 'NPTEL', description: 'IIT/IISc lecture series — free Indian MOOCs', url: 'nptel.ac.in', focus: ['Engineering', 'Science', 'Management'], indianContent: true, free: true },
  { name: 'Udemy', description: 'Affordable practical courses on every skill', url: 'udemy.com', focus: ['All fields'], indianContent: false, free: false },
  { name: 'edX', description: 'IIT Bombay, IIM Bangalore & global university courses', url: 'edx.org', focus: ['All fields'], indianContent: true, free: true },
  { name: 'Unacademy', description: 'India-specific exam prep — JEE, NEET, UPSC, CAT', url: 'unacademy.com', focus: ['Exam Prep'], indianContent: true, free: false },
  { name: 'Scaler Academy', description: 'Structured programs for software engineering careers', url: 'scaler.com', focus: ['Software Engineering'], indianContent: true, free: false },
  { name: 'UpGrad', description: 'Online degrees & certifications from Indian universities', url: 'upgrad.com', focus: ['MBA', 'Data Science', 'Tech'], indianContent: true, free: false },
  { name: 'Khan Academy', description: 'Free foundational learning for math, science, economics', url: 'khanacademy.org', focus: ['Foundations'], indianContent: false, free: true },
];

// ===== NEW: Unique Courses Database =====
export const uniqueCoursesDatabase: UniqueCourse[] = [
  { id: 'uc-1', name: 'Ethical Hacking & Cybersecurity', field: 'Technology', description: 'Learn to identify and exploit vulnerabilities in systems ethically to protect organizations from cyber threats.', whyUnique: 'Most people think hacking is illegal — ethical hacking is a highly paid, legal profession where you get paid to break into systems with permission.', skills: ['Penetration Testing', 'Network Security', 'Cryptography', 'SIEM Tools', 'Python Scripting'], careerOutcomes: [{ role: 'Penetration Tester', salaryRange: '8-25 LPA' }, { role: 'Security Analyst', salaryRange: '6-18 LPA' }, { role: 'CISO', salaryRange: '50-100 LPA' }], salaryRange: { entry: '6-12 LPA', mid: '15-35 LPA', senior: '40-80 LPA' }, growthPotential: 'Very High — 35% growth by 2027', countries: ['IN', 'US', 'GB', 'CA', 'AU', 'SG', 'AE'], similarCourses: ['uc-24'] },
  { id: 'uc-2', name: 'Space Law & Policy', field: 'Law', description: 'Study the legal frameworks governing space exploration, satellite communications, and celestial resource rights.', whyUnique: 'One of the newest legal fields — with private space companies like SpaceX and ISRO expanding, space lawyers are in huge demand but very few exist.', skills: ['International Law', 'Space Treaty Analysis', 'Regulatory Compliance', 'Policy Writing', 'Negotiation'], careerOutcomes: [{ role: 'Space Policy Analyst', salaryRange: '10-30 LPA' }, { role: 'Satellite Regulatory Specialist', salaryRange: '12-35 LPA' }, { role: 'Space Law Consultant', salaryRange: '20-50 LPA' }], salaryRange: { entry: '8-15 LPA', mid: '18-35 LPA', senior: '40-70 LPA' }, growthPotential: 'Extremely High — emerging field with few experts', countries: ['IN', 'US', 'GB', 'FR', 'DE'], similarCourses: ['uc-3'] },
  { id: 'uc-3', name: 'Marine Biology & Oceanography', field: 'Science', description: 'Study marine ecosystems, ocean chemistry, and underwater biodiversity to protect and understand our oceans.', whyUnique: 'A dream career for ocean lovers — India has 7,500+ km of coastline yet very few marine biologists. Highly specialized and deeply rewarding.', skills: ['Marine Ecology', 'Scuba Diving', 'Data Analysis', 'GIS Mapping', 'Research Methods'], careerOutcomes: [{ role: 'Marine Biologist', salaryRange: '5-15 LPA' }, { role: 'Oceanographer', salaryRange: '8-20 LPA' }, { role: 'Conservation Scientist', salaryRange: '6-18 LPA' }], salaryRange: { entry: '4-8 LPA', mid: '10-22 LPA', senior: '25-50 LPA' }, growthPotential: 'Growing — climate focus increasing demand', countries: ['IN', 'US', 'AU', 'GB', 'CA'], similarCourses: ['uc-27'] },
  { id: 'uc-4', name: 'Forensic Science & Criminology', field: 'Science', description: 'Apply scientific methods to investigate crimes — from DNA analysis to digital forensics and crime scene reconstruction.', whyUnique: 'Real-life CSI — combines science, law, and investigation. India has a massive backlog of forensic cases, creating huge demand.', skills: ['DNA Analysis', 'Crime Scene Investigation', 'Digital Forensics', 'Toxicology', 'Report Writing'], careerOutcomes: [{ role: 'Forensic Scientist', salaryRange: '5-15 LPA' }, { role: 'Digital Forensics Expert', salaryRange: '8-25 LPA' }, { role: 'Crime Scene Investigator', salaryRange: '4-12 LPA' }], salaryRange: { entry: '4-8 LPA', mid: '10-22 LPA', senior: '25-50 LPA' }, growthPotential: 'High — increasing crime complexity drives demand', countries: ['IN', 'US', 'GB', 'CA', 'AU'], similarCourses: ['uc-24'] },
  { id: 'uc-5', name: 'Actuarial Science', field: 'Finance', description: 'Use mathematics and statistics to assess risk in insurance, finance, and business — one of the highest-paying careers globally.', whyUnique: 'One of the highest-paid professions with less than 500 qualified actuaries in India — demand far exceeds supply.', skills: ['Probability & Statistics', 'Financial Mathematics', 'Risk Modeling', 'Excel/VBA', 'Actuarial Software'], careerOutcomes: [{ role: 'Actuary', salaryRange: '12-40 LPA' }, { role: 'Risk Analyst', salaryRange: '8-25 LPA' }, { role: 'Insurance Product Manager', salaryRange: '10-30 LPA' }], salaryRange: { entry: '8-15 LPA', mid: '20-45 LPA', senior: '50-100 LPA' }, growthPotential: 'Very High — massive insurance market growth', countries: ['IN', 'US', 'GB', 'CA', 'AU', 'SG'], similarCourses: [] },
  { id: 'uc-6', name: 'Nanotechnology', field: 'Engineering', description: 'Work with materials at the atomic and molecular level to create new products and technologies — from medicine to electronics.', whyUnique: 'The science of the tiny that creates huge impact — from cancer treatment to flexible screens. Very few colleges offer this, making experts rare.', skills: ['Material Science', 'Electron Microscopy', 'Nanofabrication', 'Quantum Mechanics', 'Lab Techniques'], careerOutcomes: [{ role: 'Nanotechnology Engineer', salaryRange: '6-20 LPA' }, { role: 'Research Scientist', salaryRange: '8-25 LPA' }, { role: 'R&D Manager', salaryRange: '15-40 LPA' }], salaryRange: { entry: '5-10 LPA', mid: '12-28 LPA', senior: '30-60 LPA' }, growthPotential: 'Very High — key to future technology', countries: ['IN', 'US', 'JP', 'DE', 'KR'], similarCourses: ['uc-11'] },
  { id: 'uc-7', name: 'AI Ethics & Responsible AI', field: 'Technology', description: 'Study the moral implications of AI systems — bias, fairness, privacy, and accountability in algorithmic decision-making.', whyUnique: 'As AI grows exponentially, so do ethical concerns. This emerging field combines philosophy, law, and technology — and companies are hiring urgently.', skills: ['AI/ML Fundamentals', 'Ethical Frameworks', 'Bias Detection', 'Policy Writing', 'Philosophy of Technology'], careerOutcomes: [{ role: 'AI Ethics Researcher', salaryRange: '10-30 LPA' }, { role: 'Responsible AI Manager', salaryRange: '15-40 LPA' }, { role: 'AI Policy Advisor', salaryRange: '12-35 LPA' }], salaryRange: { entry: '8-15 LPA', mid: '18-35 LPA', senior: '40-70 LPA' }, growthPotential: 'Extremely High — newest tech field', countries: ['IN', 'US', 'GB', 'CA', 'DE'], similarCourses: [] },
  { id: 'uc-8', name: 'Sommelier & Wine Studies', field: 'Hospitality', description: 'Master the art and science of wine — tasting, pairing, production, and service in the luxury hospitality industry.', whyUnique: 'A niche luxury profession with very few certified sommeliers in India — high demand in 5-star hotels, fine dining, and wine import companies.', skills: ['Wine Tasting', 'Food Pairing', 'Viticulture', 'Service Standards', 'Wine Business'], careerOutcomes: [{ role: 'Head Sommelier', salaryRange: '8-25 LPA' }, { role: 'Wine Consultant', salaryRange: '10-30 LPA' }, { role: 'Beverage Director', salaryRange: '15-40 LPA' }], salaryRange: { entry: '4-8 LPA', mid: '10-25 LPA', senior: '25-50 LPA' }, growthPotential: 'High — luxury market expanding in India', countries: ['IN', 'FR', 'IT', 'US', 'AU'], similarCourses: [] },
  { id: 'uc-9', name: 'Wildlife Conservation & Photography', field: 'Environment', description: 'Combine field conservation work with professional wildlife photography to document and protect endangered species.', whyUnique: 'Turn your love for nature into a career — India has incredible biodiversity but very few trained wildlife conservationists with visual storytelling skills.', skills: ['Wildlife Biology', 'Photography', 'GIS Mapping', 'Conservation Policy', 'Field Research'], careerOutcomes: [{ role: 'Wildlife Photographer', salaryRange: '4-15 LPA' }, { role: 'Conservation Scientist', salaryRange: '6-18 LPA' }, { role: 'National Park Manager', salaryRange: '8-20 LPA' }], salaryRange: { entry: '3-6 LPA', mid: '8-20 LPA', senior: '20-45 LPA' }, growthPotential: 'Growing — eco-tourism and conservation awareness rising', countries: ['IN', 'US', 'AU', 'KE', 'ZA'], similarCourses: ['uc-3'] },
  { id: 'uc-10', name: 'Drone Technology & Piloting', field: 'Technology', description: 'Design, operate, and manage drone systems for applications from agriculture to filmmaking, surveying, and delivery.', whyUnique: 'India just liberalized drone rules — the market is exploding but has very few certified drone pilots. Get in early for massive opportunities.', skills: ['Drone Piloting', 'Aerial Photography', 'GIS Mapping', 'Drone Programming', 'Regulatory Compliance'], careerOutcomes: [{ role: 'Drone Pilot', salaryRange: '4-12 LPA' }, { role: 'Drone Operations Manager', salaryRange: '8-20 LPA' }, { role: 'UAV Design Engineer', salaryRange: '10-25 LPA' }], salaryRange: { entry: '3-8 LPA', mid: '8-20 LPA', senior: '20-45 LPA' }, growthPotential: 'Very High — 25%+ CAGR in India', countries: ['IN', 'US', 'GB', 'AU', 'AE'], similarCourses: [] },
  { id: 'uc-11', name: 'Quantum Computing', field: 'Technology', description: 'Work with quantum mechanical phenomena to process information in fundamentally new ways, solving problems classical computers cannot.', whyUnique: 'The next revolution after AI — quantum computing is still nascent but will transform cryptography, drug discovery, and optimization. Early entrants will dominate.', skills: ['Quantum Mechanics', 'Linear Algebra', 'Python (Qiskit)', 'Quantum Algorithms', 'Circuit Design'], careerOutcomes: [{ role: 'Quantum Researcher', salaryRange: '15-40 LPA' }, { role: 'Quantum Software Engineer', salaryRange: '12-35 LPA' }, { role: 'Quantum Algorithm Designer', salaryRange: '20-50 LPA' }], salaryRange: { entry: '10-20 LPA', mid: '20-45 LPA', senior: '50-100 LPA' }, growthPotential: 'Nascent but Explosive', countries: ['IN', 'US', 'GB', 'DE', 'JP'], similarCourses: ['uc-6'] },
  { id: 'uc-12', name: 'Bioinformatics', field: 'Science', description: 'Apply computational tools to biological data — genome sequencing, protein structure, and drug discovery through data analysis.', whyUnique: 'Where biology meets coding — a rare combination that pharmaceutical and biotech companies desperately need. India has less than 1000 trained bioinformaticians.', skills: ['Python/R', 'Genomics', 'Machine Learning', 'Database Management', 'Statistical Analysis'], careerOutcomes: [{ role: 'Bioinformatics Scientist', salaryRange: '8-22 LPA' }, { role: 'Computational Biologist', salaryRange: '10-28 LPA' }, { role: 'Genomics Data Analyst', salaryRange: '6-18 LPA' }], salaryRange: { entry: '5-10 LPA', mid: '12-28 LPA', senior: '30-60 LPA' }, growthPotential: 'Very High — genomics revolution', countries: ['IN', 'US', 'GB', 'DE', 'SG'], similarCourses: [] },
  { id: 'uc-13', name: 'Sports Analytics', field: 'Sports', description: 'Use data analysis and statistics to evaluate player performance, team strategy, and business operations in sports.', whyUnique: 'Cricket, football, and IPL teams are hiring data analysts — but very few people know sports AND data science. A dream job for sports lovers.', skills: ['Statistical Modeling', 'Python/R', 'Data Visualization', 'Sports Domain Knowledge', 'Machine Learning'], careerOutcomes: [{ role: 'Sports Data Analyst', salaryRange: '6-18 LPA' }, { role: 'Performance Analyst', salaryRange: '8-22 LPA' }, { role: 'Sports Analytics Manager', salaryRange: '12-30 LPA' }], salaryRange: { entry: '5-10 LPA', mid: '10-25 LPA', senior: '25-50 LPA' }, growthPotential: 'High — sports industry embracing data', countries: ['IN', 'US', 'GB', 'AU'], similarCourses: [] },
  { id: 'uc-14', name: 'UX Research & Cognitive Psychology', field: 'Design', description: 'Study human cognition and behavior to design better digital products — understand how people think, decide, and interact with technology.', whyUnique: 'UX Research is not just design — it is psychology applied to products. Companies pay a premium for researchers who understand human behavior deeply.', skills: ['User Research Methods', 'Cognitive Psychology', 'Usability Testing', 'Data Analysis', 'Prototyping'], careerOutcomes: [{ role: 'UX Researcher', salaryRange: '8-22 LPA' }, { role: 'Design Research Lead', salaryRange: '15-35 LPA' }, { role: 'Chief Design Officer', salaryRange: '40-80 LPA' }], salaryRange: { entry: '6-12 LPA', mid: '15-30 LPA', senior: '35-70 LPA' }, growthPotential: 'High — design maturity growing', countries: ['IN', 'US', 'GB', 'CA', 'DE'], similarCourses: [] },
  { id: 'uc-15', name: 'Gemology', field: 'Luxury', description: 'Study precious and semi-precious gems — identification, grading, valuation, and treatment for the jewelry and luxury industry.', whyUnique: 'A rare specialization that combines science with luxury — India is the world\'s largest gem cutting center, yet has very few certified gemologists.', skills: ['Gem Identification', 'Grading Systems', 'Microscopy', 'Valuation', 'Jewelry Design'], careerOutcomes: [{ role: 'Gemologist', salaryRange: '5-15 LPA' }, { role: 'Jewelry Appraiser', salaryRange: '6-20 LPA' }, { role: 'Gem Lab Director', salaryRange: '12-30 LPA' }], salaryRange: { entry: '4-8 LPA', mid: '10-22 LPA', senior: '25-50 LPA' }, growthPotential: 'Stable — luxury market always needs experts', countries: ['IN', 'US', 'GB', 'AE', 'CH'], similarCourses: [] },
  { id: 'uc-16', name: 'Agricultural Technology', field: 'Agriculture', description: 'Apply technology to revolutionize farming — IoT sensors, drone mapping, AI crop prediction, and precision agriculture.', whyUnique: 'India is an agricultural country but AgriTech is just starting — huge opportunity to combine technology with the largest employment sector.', skills: ['IoT & Sensors', 'Drone Technology', 'Data Analytics', 'Crop Science', 'Precision Farming'], careerOutcomes: [{ role: 'AgriTech Engineer', salaryRange: '5-15 LPA' }, { role: 'Precision Farming Specialist', salaryRange: '6-18 LPA' }, { role: 'AgriTech Startup Founder', salaryRange: 'Variable' }], salaryRange: { entry: '4-8 LPA', mid: '10-22 LPA', senior: '22-45 LPA' }, growthPotential: 'Very High — government pushing AgriTech', countries: ['IN', 'US', 'AU', 'BR', 'KE'], similarCourses: ['uc-10'] },
  { id: 'uc-17', name: 'Heritage Conservation & Restoration', field: 'Culture', description: 'Preserve and restore historical monuments, artifacts, and cultural heritage sites using modern conservation techniques.', whyUnique: 'India has 40 UNESCO World Heritage Sites but a severe shortage of trained conservators — combine art, science, and history in this unique career.', skills: ['Conservation Science', 'Art History', 'Chemical Analysis', 'Restoration Techniques', 'Documentation'], careerOutcomes: [{ role: 'Conservation Architect', salaryRange: '5-15 LPA' }, { role: 'Art Restorer', salaryRange: '4-12 LPA' }, { role: 'Heritage Manager', salaryRange: '6-18 LPA' }], salaryRange: { entry: '3-6 LPA', mid: '8-18 LPA', senior: '18-35 LPA' }, growthPotential: 'Growing — heritage tourism expanding', countries: ['IN', 'IT', 'GB', 'FR', 'EG'], similarCourses: [] },
  { id: 'uc-18', name: 'Podcast Production & Audio Storytelling', field: 'Media', description: 'Create compelling audio content — from concept and scripting to recording, editing, and distributing professional podcasts.', whyUnique: 'The podcast industry in India is booming (3x growth in 3 years) but there are very few trained professionals. Be the first wave of audio creators.', skills: ['Audio Editing', 'Script Writing', 'Sound Design', 'Interviewing', 'Distribution Strategy'], careerOutcomes: [{ role: 'Podcast Producer', salaryRange: '4-12 LPA' }, { role: 'Audio Content Strategist', salaryRange: '6-18 LPA' }, { role: 'Podcast Network Manager', salaryRange: '10-25 LPA' }], salaryRange: { entry: '3-6 LPA', mid: '8-18 LPA', senior: '18-35 LPA' }, growthPotential: 'Very High — audio content exploding', countries: ['IN', 'US', 'GB', 'AU', 'CA'], similarCourses: [] },
  { id: 'uc-19', name: 'Climate Science & Sustainability', field: 'Environment', description: 'Study climate systems, model future scenarios, and develop strategies for sustainable development and carbon reduction.', whyUnique: 'The hottest career of the decade — every major company now needs sustainability experts, but supply is extremely limited.', skills: ['Climate Modeling', 'Carbon Accounting', 'Sustainability Reporting', 'Data Analysis', 'Policy Development'], careerOutcomes: [{ role: 'Climate Analyst', salaryRange: '6-18 LPA' }, { role: 'Sustainability Consultant', salaryRange: '10-28 LPA' }, { role: 'ESG Director', salaryRange: '25-60 LPA' }], salaryRange: { entry: '5-10 LPA', mid: '12-28 LPA', senior: '30-60 LPA' }, growthPotential: 'Extremely High — ESG mandate expanding', countries: ['IN', 'US', 'GB', 'DE', 'NL'], similarCourses: ['uc-3'] },
  { id: 'uc-20', name: 'Digital Forensics & Incident Response', field: 'Technology', description: 'Investigate cybercrime, analyze digital evidence, and respond to security breaches to protect organizations.', whyUnique: 'Cybercrime is rising 300% year-on-year in India — but there are fewer than 500 certified digital forensics experts in the entire country.', skills: ['Disk Forensics', 'Network Forensics', 'Memory Analysis', 'Incident Response', 'Malware Analysis'], careerOutcomes: [{ role: 'Digital Forensics Examiner', salaryRange: '8-22 LPA' }, { role: 'Incident Response Lead', salaryRange: '12-30 LPA' }, { role: 'Cybersecurity Director', salaryRange: '30-70 LPA' }], salaryRange: { entry: '6-12 LPA', mid: '15-30 LPA', senior: '35-70 LPA' }, growthPotential: 'Very High — cybercrime increasing', countries: ['IN', 'US', 'GB', 'CA', 'AU'], similarCourses: ['uc-1'] },
  { id: 'uc-21', name: 'Astrobiology', field: 'Science', description: 'Study the possibility of life beyond Earth — extremophiles, planetary habitability, and the search for extraterrestrial life.', whyUnique: 'Literally the study of alien life — ISRO, NASA, and ESA are investing billions. A field that captures imagination and has real career potential.', skills: ['Microbiology', 'Planetary Science', 'Biochemistry', 'Data Analysis', 'Research Methods'], careerOutcomes: [{ role: 'Astrobiology Researcher', salaryRange: '8-22 LPA' }, { role: 'Planetary Scientist', salaryRange: '10-28 LPA' }, { role: 'Space Mission Analyst', salaryRange: '12-30 LPA' }], salaryRange: { entry: '6-12 LPA', mid: '12-28 LPA', senior: '25-50 LPA' }, growthPotential: 'Emerging — space exploration expanding', countries: ['IN', 'US', 'GB', 'DE', 'JP'], similarCourses: ['uc-2'] },
  { id: 'uc-22', name: 'Music Therapy', field: 'Healthcare', description: 'Use music clinically to address physical, emotional, cognitive, and social needs of individuals in healthcare and rehabilitation.', whyUnique: 'An ancient healing art now backed by modern science — India has a rich musical tradition but fewer than 200 certified music therapists.', skills: ['Music Theory', 'Clinical Assessment', 'Therapeutic Techniques', 'Psychology', 'Patient Communication'], careerOutcomes: [{ role: 'Music Therapist', salaryRange: '4-12 LPA' }, { role: 'Rehabilitation Specialist', salaryRange: '5-15 LPA' }, { role: 'Wellness Program Director', salaryRange: '8-22 LPA' }], salaryRange: { entry: '3-6 LPA', mid: '8-18 LPA', senior: '18-35 LPA' }, growthPotential: 'Growing — alternative medicine gaining acceptance', countries: ['IN', 'US', 'GB', 'AU', 'CA'], similarCourses: [] },
  { id: 'uc-23', name: 'Epidemiology & Public Health', field: 'Healthcare', description: 'Study disease patterns, outbreak investigation, and public health policy to prevent and control epidemics.', whyUnique: 'Post-COVID, epidemiologists are superheroes — but India has a severe shortage. This field offers stable government and international organization careers.', skills: ['Biostatistics', 'Outbreak Investigation', 'Epidemiological Methods', 'Public Health Policy', 'Data Analysis'], careerOutcomes: [{ role: 'Epidemiologist', salaryRange: '6-18 LPA' }, { role: 'Public Health Director', salaryRange: '10-25 LPA' }, { role: 'WHO Consultant', salaryRange: '15-40 LPA' }], salaryRange: { entry: '5-10 LPA', mid: '10-22 LPA', senior: '22-50 LPA' }, growthPotential: 'High — post-pandemic focus on public health', countries: ['IN', 'US', 'GB', 'KE', 'CH'], similarCourses: [] },
  { id: 'uc-24', name: 'Renewable Energy Engineering', field: 'Engineering', description: 'Design and implement solar, wind, hydrogen, and other renewable energy systems to combat climate change.', whyUnique: 'India is the 4th largest renewable energy market — the country needs 1 million green energy professionals by 2030 but has less than 100,000 today.', skills: ['Solar PV Design', 'Wind Energy Systems', 'Grid Integration', 'Energy Storage', 'Project Management'], careerOutcomes: [{ role: 'Renewable Energy Engineer', salaryRange: '6-18 LPA' }, { role: 'Solar Project Manager', salaryRange: '10-25 LPA' }, { role: 'Green Energy Director', salaryRange: '20-50 LPA' }], salaryRange: { entry: '5-10 LPA', mid: '12-25 LPA', senior: '25-55 LPA' }, growthPotential: 'Extremely High — 500 GW target by 2030', countries: ['IN', 'US', 'DE', 'CN', 'AU'], similarCourses: ['uc-19'] },
  { id: 'uc-25', name: 'Computational Linguistics & NLP', field: 'Technology', description: 'Bridge language and computing — build systems that understand, process, and generate human language for AI applications.', whyUnique: 'Indic language NLP is a wide-open field — 22 official languages, billions of speakers, but very few computational linguists. Massive opportunity in Indian languages.', skills: ['Linguistics', 'Python', 'NLP Models', 'Machine Learning', 'Phonetics/Syntax'], careerOutcomes: [{ role: 'NLP Engineer', salaryRange: '8-25 LPA' }, { role: 'Computational Linguist', salaryRange: '10-28 LPA' }, { role: 'AI Language Scientist', salaryRange: '15-40 LPA' }], salaryRange: { entry: '6-12 LPA', mid: '15-30 LPA', senior: '30-60 LPA' }, growthPotential: 'Very High — Indic AI is exploding', countries: ['IN', 'US', 'GB', 'DE'], similarCourses: ['uc-7'] },
  { id: 'uc-26', name: 'Sports Science & Biomechanics', field: 'Sports', description: 'Apply scientific principles to athletic performance — injury prevention, nutrition, training optimization, and recovery.', whyUnique: 'Indian sports are professionalizing rapidly (IPL, ISL, PKL) — but sports science infrastructure is still nascent. Be a pioneer in this field.', skills: ['Exercise Physiology', 'Biomechanics', 'Sports Nutrition', 'Performance Analysis', 'Rehabilitation'], careerOutcomes: [{ role: 'Sports Scientist', salaryRange: '5-15 LPA' }, { role: 'Strength & Conditioning Coach', salaryRange: '6-18 LPA' }, { role: 'Sports Medicine Specialist', salaryRange: '10-30 LPA' }], salaryRange: { entry: '4-8 LPA', mid: '8-20 LPA', senior: '20-40 LPA' }, growthPotential: 'High — sports professionalization growing', countries: ['IN', 'US', 'GB', 'AU', 'DE'], similarCourses: ['uc-13'] },
  { id: 'uc-27', name: 'Ocean Engineering & Marine Tech', field: 'Engineering', description: 'Design and build systems for ocean exploration — underwater robots, offshore platforms, and marine renewable energy.', whyUnique: 'Blue economy is the next frontier — India has a massive exclusive economic zone but very few ocean engineers.', skills: ['Marine Engineering', 'ROV Design', 'Offshore Structures', 'Ocean Dynamics', 'CAD/CAM'], careerOutcomes: [{ role: 'Ocean Engineer', salaryRange: '8-22 LPA' }, { role: 'Offshore Project Manager', salaryRange: '12-30 LPA' }, { role: 'Marine Systems Designer', salaryRange: '10-25 LPA' }], salaryRange: { entry: '6-12 LPA', mid: '12-28 LPA', senior: '25-55 LPA' }, growthPotential: 'Growing — blue economy focus', countries: ['IN', 'US', 'NO', 'GB', 'AU'], similarCourses: ['uc-3'] },
  { id: 'uc-28', name: 'Robotics & Autonomous Systems', field: 'Engineering', description: 'Build intelligent robots for manufacturing, healthcare, defense, and household applications — the intersection of AI, mechanics, and electronics.', whyUnique: 'India\'s robotics market is growing 20%+ annually but talent is scarce. This combines multiple engineering disciplines into one exciting field.', skills: ['Robot Operating System (ROS)', 'Computer Vision', 'Control Systems', '3D Printing', 'AI/ML'], careerOutcomes: [{ role: 'Robotics Engineer', salaryRange: '8-22 LPA' }, { role: 'Automation Architect', salaryRange: '12-30 LPA' }, { role: 'Robotics Startup Founder', salaryRange: 'Variable' }], salaryRange: { entry: '6-12 LPA', mid: '15-30 LPA', senior: '30-60 LPA' }, growthPotential: 'Very High — Industry 4.0 adoption', countries: ['IN', 'US', 'JP', 'DE', 'KR'], similarCourses: ['uc-11'] },
  { id: 'uc-29', name: 'Culinary Science & Food Innovation', field: 'Food', description: 'Combine cooking artistry with food science — molecular gastronomy, food tech, plant-based proteins, and sustainable food systems.', whyUnique: 'Food tech startups raised $2B+ in India — but very few people combine culinary skills with scientific innovation. Be a food entrepreneur of the future.', skills: ['Food Chemistry', 'Molecular Gastronomy', 'Product Development', 'Sensory Analysis', 'Food Safety'], careerOutcomes: [{ role: 'Food Technologist', salaryRange: '5-15 LPA' }, { role: 'Culinary Innovation Manager', salaryRange: '8-22 LPA' }, { role: 'Food Startup Founder', salaryRange: 'Variable' }], salaryRange: { entry: '4-8 LPA', mid: '10-22 LPA', senior: '22-45 LPA' }, growthPotential: 'High — food tech booming', countries: ['IN', 'US', 'GB', 'FR', 'AU'], similarCourses: [] },
  { id: 'uc-30', name: 'Human-Computer Interaction (HCI)', field: 'Design', description: 'Design the future of how humans interact with technology — AR/VR, voice interfaces, brain-computer interfaces, and spatial computing.', whyUnique: 'The next generation of interfaces goes beyond screens — AR/VR, spatial computing, and brain-computer interfaces need HCI experts who don\'t exist yet.', skills: ['Interaction Design', 'AR/VR Design', 'Usability Engineering', 'Prototyping', 'Cognitive Science'], careerOutcomes: [{ role: 'HCI Designer', salaryRange: '8-22 LPA' }, { role: 'XR Experience Designer', salaryRange: '10-28 LPA' }, { role: 'Head of Design Innovation', salaryRange: '25-55 LPA' }], salaryRange: { entry: '6-12 LPA', mid: '15-30 LPA', senior: '30-60 LPA' }, growthPotential: 'Very High — spatial computing era', countries: ['IN', 'US', 'GB', 'CA', 'DE'], similarCourses: ['uc-14'] },
];

// ===== NEW: Institution Database =====
export const institutionDatabase: Institution[] = [
  { id: 'inst-1', name: 'IIT Bombay', type: 'university', location: { city: 'Mumbai', state: 'Maharashtra', country: 'IN', tier: 'metro' }, ranking: { national: 1, state: 1 }, courses: ['uc-1', 'uc-6', 'uc-11', 'uc-12', 'uc-28'], fees: { tuition: '2.2 LPA', hostel: '30K/year', application: '300' }, placementRate: 95, avgPlacementSalary: '21.7 LPA', topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Goldman Sachs', 'McKinsey'], startDate: 'Aug 2026', url: 'iitb.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-2', name: 'IIT Delhi', type: 'university', location: { city: 'New Delhi', state: 'Delhi', country: 'IN', tier: 'metro' }, ranking: { national: 2, state: 1 }, courses: ['uc-1', 'uc-5', 'uc-6', 'uc-24', 'uc-28'], fees: { tuition: '2.2 LPA', hostel: '28K/year', application: '300' }, placementRate: 93, avgPlacementSalary: '20.5 LPA', topRecruiters: ['Google', 'Microsoft', 'Flipkart', 'BCG', 'Deloitte'], startDate: 'Aug 2026', url: 'iitd.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-3', name: 'IIT Madras', type: 'university', location: { city: 'Chennai', state: 'Tamil Nadu', country: 'IN', tier: 'metro' }, ranking: { national: 3, state: 1 }, courses: ['uc-1', 'uc-6', 'uc-11', 'uc-24', 'uc-28'], fees: { tuition: '2.2 LPA', hostel: '25K/year', application: '300' }, placementRate: 94, avgPlacementSalary: '19.8 LPA', topRecruiters: ['Google', 'Amazon', 'Microsoft', 'Qualcomm', 'L&T'], startDate: 'Aug 2026', url: 'iitm.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-4', name: 'IIT Kanpur', type: 'university', location: { city: 'Kanpur', state: 'Uttar Pradesh', country: 'IN', tier: 'tier-1' }, ranking: { national: 4, state: 1 }, courses: ['uc-1', 'uc-6', 'uc-11', 'uc-25'], fees: { tuition: '2.2 LPA', hostel: '22K/year', application: '300' }, placementRate: 90, avgPlacementSalary: '18.5 LPA', topRecruiters: ['Microsoft', 'Google', 'Amazon', 'Adobe', 'Oracle'], startDate: 'Aug 2026', url: 'iitk.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-5', name: 'IIT Kharagpur', type: 'university', location: { city: 'Kharagpur', state: 'West Bengal', country: 'IN', tier: 'tier-2' }, ranking: { national: 5, state: 1 }, courses: ['uc-1', 'uc-6', 'uc-16', 'uc-24', 'uc-28'], fees: { tuition: '2.2 LPA', hostel: '20K/year', application: '300' }, placementRate: 88, avgPlacementSalary: '18.2 LPA', topRecruiters: ['Google', 'Microsoft', 'Amazon', 'TCS', 'Wipro'], startDate: 'Aug 2026', url: 'iitkgp.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-6', name: 'IIM Ahmedabad', type: 'university', location: { city: 'Ahmedabad', state: 'Gujarat', country: 'IN', tier: 'metro' }, ranking: { national: 1, state: 1 }, courses: ['uc-5', 'uc-13'], fees: { tuition: '12 LPA', hostel: '1.5L/year', application: '2000' }, placementRate: 98, avgPlacementSalary: '35.5 LPA', topRecruiters: ['McKinsey', 'BCG', 'Goldman Sachs', 'Amazon', 'Flipkart'], startDate: 'June 2026', url: 'iima.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-7', name: 'IIM Bangalore', type: 'university', location: { city: 'Bangalore', state: 'Karnataka', country: 'IN', tier: 'metro' }, ranking: { national: 2, state: 1 }, courses: ['uc-5', 'uc-13', 'uc-19'], fees: { tuition: '12 LPA', hostel: '1.4L/year', application: '2000' }, placementRate: 97, avgPlacementSalary: '33.8 LPA', topRecruiters: ['McKinsey', 'Bain', 'Amazon', 'Microsoft', 'Deloitte'], startDate: 'June 2026', url: 'iimb.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-8', name: 'BITS Pilani', type: 'university', location: { city: 'Pilani', state: 'Rajasthan', country: 'IN', tier: 'tier-3' }, ranking: { national: 11, state: 1 }, courses: ['uc-1', 'uc-6', 'uc-11', 'uc-25', 'uc-28'], fees: { tuition: '5.2 LPA', hostel: '60K/year', application: '3500' }, placementRate: 85, avgPlacementSalary: '16.2 LPA', topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Deloitte', 'Adobe'], startDate: 'Aug 2026', url: 'bits-pilani.ac.in', accreditation: 'UGC, NAAC A' },
  { id: 'inst-9', name: 'VIT Vellore', type: 'university', location: { city: 'Vellore', state: 'Tamil Nadu', country: 'IN', tier: 'tier-2' }, ranking: { national: 12, state: 2 }, courses: ['uc-1', 'uc-6', 'uc-24', 'uc-28'], fees: { tuition: '3.5 LPA', hostel: '80K/year', application: '1200' }, placementRate: 78, avgPlacementSalary: '8.5 LPA', topRecruiters: ['TCS', 'Infosys', 'Wipro', 'Amazon', 'Cognizant'], startDate: 'July 2026', url: 'vit.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-10', name: 'IIIT Hyderabad', type: 'university', location: { city: 'Hyderabad', state: 'Telangana', country: 'IN', tier: 'metro' }, ranking: { national: 14, state: 1 }, courses: ['uc-1', 'uc-7', 'uc-11', 'uc-25'], fees: { tuition: '3 LPA', hostel: '50K/year', application: '1500' }, placementRate: 92, avgPlacementSalary: '22 LPA', topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Facebook', 'Adobe'], startDate: 'Aug 2026', url: 'iiit.ac.in', accreditation: 'UGC, NAAC A' },
  { id: 'inst-11', name: 'NIT Trichy', type: 'university', location: { city: 'Tiruchirappalli', state: 'Tamil Nadu', country: 'IN', tier: 'tier-2' }, ranking: { national: 9, state: 3 }, courses: ['uc-1', 'uc-6', 'uc-24'], fees: { tuition: '1.5 LPA', hostel: '20K/year', application: '200' }, placementRate: 82, avgPlacementSalary: '12.5 LPA', topRecruiters: ['TCS', 'Infosys', 'Google', 'Amazon', 'L&T'], startDate: 'Aug 2026', url: 'nitt.edu', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-12', name: 'SRM University', type: 'university', location: { city: 'Chennai', state: 'Tamil Nadu', country: 'IN', tier: 'metro' }, ranking: { national: 25, state: 4 }, courses: ['uc-1', 'uc-6', 'uc-9', 'uc-28'], fees: { tuition: '3.5 LPA', hostel: '1L/year', application: '1100' }, placementRate: 70, avgPlacementSalary: '6 LPA', topRecruiters: ['TCS', 'Infosys', 'Wipro', 'Cognizant', 'Amazon'], startDate: 'July 2026', url: 'srmist.edu.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-13', name: 'Amity University', type: 'university', location: { city: 'Noida', state: 'Uttar Pradesh', country: 'IN', tier: 'metro' }, ranking: { national: 35, state: 5 }, courses: ['uc-1', 'uc-4', 'uc-7', 'uc-8', 'uc-22'], fees: { tuition: '4 LPA', hostel: '1.2L/year', application: '1500' }, placementRate: 65, avgPlacementSalary: '5 LPA', topRecruiters: ['TCS', 'HCL', 'Wipro', 'Infosys', 'Amazon'], startDate: 'Aug 2026', url: 'amity.edu', accreditation: 'UGC, NAAC A+' },
  { id: 'inst-14', name: 'JNU Delhi', type: 'university', location: { city: 'New Delhi', state: 'Delhi', country: 'IN', tier: 'metro' }, ranking: { national: 2, state: 2 }, courses: ['uc-2', 'uc-21', 'uc-23', 'uc-25'], fees: { tuition: '500/year', hostel: '10K/year', application: '300' }, placementRate: 75, avgPlacementSalary: '8 LPA', topRecruiters: ['UN Organizations', 'Government', 'Think Tanks', 'Universities'], startDate: 'Aug 2026', url: 'jnu.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-15', name: 'AIIMS New Delhi', type: 'university', location: { city: 'New Delhi', state: 'Delhi', country: 'IN', tier: 'metro' }, ranking: { national: 1, state: 1 }, courses: ['uc-4', 'uc-12', 'uc-22', 'uc-23'], fees: { tuition: '1.5K/year', hostel: '5K/year', application: '1500' }, placementRate: 99, avgPlacementSalary: 'N/A (Govt)', topRecruiters: ['AIIMS', 'Apollo', 'Fortis', 'Government Hospitals'], startDate: 'Aug 2026', url: 'aiims.edu', accreditation: 'UGC, NMC' },
  { id: 'inst-16', name: 'NIFT Delhi', type: 'university', location: { city: 'New Delhi', state: 'Delhi', country: 'IN', tier: 'metro' }, ranking: { national: 1, state: 1 }, courses: ['uc-15'], fees: { tuition: '3.5 LPA', hostel: '60K/year', application: '1500' }, placementRate: 85, avgPlacementSalary: '7 LPA', topRecruiters: ['Titan', 'Reliance Brands', 'Raymond', 'Aditya Birla Fashion'], startDate: 'Aug 2026', url: 'nift.ac.in', accreditation: 'UGC, NAAC A' },
  { id: 'inst-17', name: 'NLSIU Bangalore', type: 'university', location: { city: 'Bangalore', state: 'Karnataka', country: 'IN', tier: 'metro' }, ranking: { national: 1, state: 1 }, courses: ['uc-2'], fees: { tuition: '2.5 LPA', hostel: '50K/year', application: '1500' }, placementRate: 95, avgPlacementSalary: '18 LPA', topRecruiters: ['Supreme Court', 'Cyril Amarchand', 'AZB Partners', 'Khaitan & Co'], startDate: 'Aug 2026', url: 'nlsiu.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-18', name: 'University of Hyderabad', type: 'university', location: { city: 'Hyderabad', state: 'Telangana', country: 'IN', tier: 'metro' }, ranking: { national: 10, state: 2 }, courses: ['uc-3', 'uc-9', 'uc-21', 'uc-25'], fees: { tuition: '30K/year', hostel: '15K/year', application: '500' }, placementRate: 70, avgPlacementSalary: '6 LPA', topRecruiters: ['DRDO', 'ISRO', 'Universities', 'TCS'], startDate: 'Aug 2026', url: 'uohyd.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-19', name: 'IIT Roorkee', type: 'university', location: { city: 'Roorkee', state: 'Uttarakhand', country: 'IN', tier: 'tier-2' }, ranking: { national: 6, state: 1 }, courses: ['uc-1', 'uc-24', 'uc-27', 'uc-28'], fees: { tuition: '2.2 LPA', hostel: '20K/year', application: '300' }, placementRate: 86, avgPlacementSalary: '17.8 LPA', topRecruiters: ['Google', 'Microsoft', 'L&T', 'TCS', 'Amazon'], startDate: 'Aug 2026', url: 'iitr.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-20', name: 'Pune University (Savitribai Phule)', type: 'university', location: { city: 'Pune', state: 'Maharashtra', country: 'IN', tier: 'metro' }, ranking: { national: 20, state: 3 }, courses: ['uc-4', 'uc-9', 'uc-23'], fees: { tuition: '50K/year', hostel: '12K/year', application: '300' }, placementRate: 55, avgPlacementSalary: '4.5 LPA', topRecruiters: ['TCS', 'Wipro', 'Infosys', 'Cognizant'], startDate: 'Aug 2026', url: 'unipune.ac.in', accreditation: 'UGC, NAAC A' },
  { id: 'inst-21', name: 'Jadavpur University', type: 'university', location: { city: 'Kolkata', state: 'West Bengal', country: 'IN', tier: 'metro' }, ranking: { national: 13, state: 2 }, courses: ['uc-1', 'uc-4', 'uc-24'], fees: { tuition: '2.4K/year', hostel: '300/month', application: '100' }, placementRate: 72, avgPlacementSalary: '8 LPA', topRecruiters: ['TCS', 'IBM', 'Google', 'Amazon', 'Cognizant'], startDate: 'Aug 2026', url: 'jaduniv.edu.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-22', name: 'Manipal University', type: 'university', location: { city: 'Manipal', state: 'Karnataka', country: 'IN', tier: 'tier-2' }, ranking: { national: 18, state: 3 }, courses: ['uc-1', 'uc-6', 'uc-8', 'uc-26'], fees: { tuition: '4 LPA', hostel: '1L/year', application: '2000' }, placementRate: 72, avgPlacementSalary: '6.5 LPA', topRecruiters: ['TCS', 'Infosys', 'Wipro', 'Amazon', 'Deloitte'], startDate: 'Aug 2026', url: 'manipal.edu', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-23', name: 'Cochin University of Science & Technology', type: 'university', location: { city: 'Kochi', state: 'Kerala', country: 'IN', tier: 'tier-2' }, ranking: { national: 30, state: 1 }, courses: ['uc-3', 'uc-27'], fees: { tuition: '75K/year', hostel: '15K/year', application: '800' }, placementRate: 60, avgPlacementSalary: '5 LPA', topRecruiters: ['TCS', 'Infosys', 'Cochin Shipyard', 'ISRO'], startDate: 'Aug 2026', url: 'cusat.ac.in', accreditation: 'UGC, NAAC A' },
  { id: 'inst-24', name: 'Government Polytechnic Mumbai', type: 'polytechnic', location: { city: 'Mumbai', state: 'Maharashtra', country: 'IN', tier: 'metro' }, ranking: { national: null, state: 5 }, courses: ['uc-10', 'uc-16'], fees: { tuition: '8K/year', hostel: null, application: '100' }, placementRate: 55, avgPlacementSalary: '3 LPA', topRecruiters: ['L&T', 'TCS', 'Local Industries'], startDate: 'Aug 2026', url: 'gp Mumbai.org', accreditation: 'AICTE, MSBTE' },
  { id: 'inst-25', name: 'District Polytechnic Varanasi', type: 'polytechnic', location: { city: 'Varanasi', state: 'Uttar Pradesh', country: 'IN', tier: 'tier-2' }, ranking: { national: null, state: 15 }, courses: ['uc-10', 'uc-16'], fees: { tuition: '5K/year', hostel: null, application: '50' }, placementRate: 40, avgPlacementSalary: '2.5 LPA', topRecruiters: ['Local Industries', 'State PWD', 'Small Manufacturing'], startDate: 'Aug 2026', url: 'bteup.ac.in', accreditation: 'AICTE' },
  { id: 'inst-26', name: 'NPTEL (Online)', type: 'training_center', location: { city: 'Online', state: 'All India', country: 'IN', tier: 'metro' }, ranking: { national: null, state: null }, courses: ['uc-1', 'uc-6', 'uc-11', 'uc-12', 'uc-24', 'uc-25'], fees: { tuition: 'Free', hostel: null, application: '0' }, placementRate: null, avgPlacementSalary: null, topRecruiters: ['Certification Value'], startDate: 'Enroll Anytime', url: 'nptel.ac.in', accreditation: 'IIT/IISc' },
  { id: 'inst-27', name: 'SWAYAM (Online)', type: 'training_center', location: { city: 'Online', state: 'All India', country: 'IN', tier: 'metro' }, ranking: { national: null, state: null }, courses: ['uc-7', 'uc-19', 'uc-23', 'uc-25'], fees: { tuition: 'Free', hostel: null, application: '0' }, placementRate: null, avgPlacementSalary: null, topRecruiters: ['Certification Value'], startDate: 'Enroll Anytime', url: 'swayam.gov.in', accreditation: 'MHRD, Govt of India' },
  { id: 'inst-28', name: 'Christ University', type: 'university', location: { city: 'Bangalore', state: 'Karnataka', country: 'IN', tier: 'metro' }, ranking: { national: 22, state: 4 }, courses: ['uc-4', 'uc-8', 'uc-22'], fees: { tuition: '2.5 LPA', hostel: '80K/year', application: '1000' }, placementRate: 68, avgPlacementSalary: '5.5 LPA', topRecruiters: ['EY', 'Deloitte', 'KPMG', 'Infosys'], startDate: 'Aug 2026', url: 'christuniversity.in', accreditation: 'UGC, NAAC A+' },
  { id: 'inst-29', name: 'Tata Institute of Social Sciences', type: 'university', location: { city: 'Mumbai', state: 'Maharashtra', country: 'IN', tier: 'metro' }, ranking: { national: 8, state: 2 }, courses: ['uc-4', 'uc-9', 'uc-19', 'uc-23'], fees: { tuition: '60K/year', hostel: '20K/year', application: '1000' }, placementRate: 82, avgPlacementSalary: '7 LPA', topRecruiters: ['NGOs', 'UNICEF', 'World Bank', 'Government'], startDate: 'Aug 2026', url: 'tiss.edu', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-30', name: 'Coursera (Online Platform)', type: 'training_center', location: { city: 'Online', state: 'Global', country: 'IN', tier: 'metro' }, ranking: { national: null, state: null }, courses: ['uc-1', 'uc-7', 'uc-11', 'uc-12', 'uc-14', 'uc-25', 'uc-30'], fees: { tuition: '3K-10K/course', hostel: null, application: '0' }, placementRate: null, avgPlacementSalary: null, topRecruiters: ['Certification Value'], startDate: 'Enroll Anytime', url: 'coursera.org', accreditation: 'University Partners' },
  { id: 'inst-31', name: 'Anna University', type: 'university', location: { city: 'Chennai', state: 'Tamil Nadu', country: 'IN', tier: 'metro' }, ranking: { national: 15, state: 2 }, courses: ['uc-1', 'uc-6', 'uc-24', 'uc-28'], fees: { tuition: '50K/year', hostel: '15K/year', application: '600' }, placementRate: 65, avgPlacementSalary: '5.5 LPA', topRecruiters: ['TCS', 'Infosys', 'Wipro', 'Cognizant', 'HCL'], startDate: 'Aug 2026', url: 'annauniv.edu', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-32', name: 'IISc Bangalore', type: 'university', location: { city: 'Bangalore', state: 'Karnataka', country: 'IN', tier: 'metro' }, ranking: { national: 1, state: 1 }, courses: ['uc-6', 'uc-11', 'uc-12', 'uc-21'], fees: { tuition: '30K/year', hostel: '15K/year', application: '800' }, placementRate: 90, avgPlacementSalary: '18 LPA', topRecruiters: ['Google Research', 'Microsoft Research', 'ISRO', 'DRDO'], startDate: 'Aug 2026', url: 'iisc.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-33', name: 'Banaras Hindu University', type: 'university', location: { city: 'Varanasi', state: 'Uttar Pradesh', country: 'IN', tier: 'tier-2' }, ranking: { national: 7, state: 2 }, courses: ['uc-4', 'uc-12', 'uc-22', 'uc-23'], fees: { tuition: '15K/year', hostel: '5K/year', application: '500' }, placementRate: 68, avgPlacementSalary: '6 LPA', topRecruiters: ['TCS', 'AIIMS', 'Government', 'DRDO'], startDate: 'Aug 2026', url: 'bhu.ac.in', accreditation: 'UGC, NAAC A++' },
  { id: 'inst-34', name: 'Training Center Palwal', type: 'training_center', location: { city: 'Palwal', state: 'Haryana', country: 'IN', tier: 'village' }, ranking: { national: null, state: null }, courses: ['uc-10', 'uc-16'], fees: { tuition: '2K/month', hostel: null, application: '0' }, placementRate: 30, avgPlacementSalary: '2 LPA', topRecruiters: ['Local Businesses', 'Agriculture Firms'], startDate: 'Monthly Batches', url: 'hsspp.gov.in', accreditation: 'HSSC' },
  { id: 'inst-35', name: 'Skill India Center Ratlam', type: 'training_center', location: { city: 'Ratlam', state: 'Madhya Pradesh', country: 'IN', tier: 'tier-3' }, ranking: { national: null, state: null }, courses: ['uc-10', 'uc-16', 'uc-29'], fees: { tuition: 'Free', hostel: null, application: '0' }, placementRate: 25, avgPlacementSalary: '1.8 LPA', topRecruiters: ['Local Industries', 'PMKVY Partners'], startDate: 'Monthly Batches', url: 'skillindia.gov.in', accreditation: 'NSDC' },
];

// ===== NEW: Internship Database =====
export const internshipDatabase: Internship[] = [
  { id: 'int-1', title: 'Software Engineering Intern', company: 'Google India', location: 'Bangalore', duration: '3 months', stipend: '40K/month', applyBy: 'Mar 15, 2026', skills: ['Python', 'Data Structures', 'Algorithms'], field: 'technology', url: 'careers.google.com', country: 'IN', description: 'Work on real Google products alongside experienced engineers. Get mentorship from senior SWEs and contribute to systems used by billions.' },
  { id: 'int-2', title: 'ML Research Intern', company: 'Microsoft Research', location: 'Bangalore', duration: '4 months', stipend: '50K/month', applyBy: 'Feb 28, 2026', skills: ['Python', 'PyTorch', 'Research Papers'], field: 'ai_ml', url: 'careers.microsoft.com', country: 'IN', description: 'Conduct cutting-edge AI research with world-class scientists. Publish papers and contribute to Microsoft AI products.' },
  { id: 'int-3', title: 'Data Science Intern', company: 'Amazon India', location: 'Hyderabad', duration: '3 months', stipend: '35K/month', applyBy: 'Apr 1, 2026', skills: ['Python', 'SQL', 'Statistics', 'ML'], field: 'ai_ml', url: 'amazon.jobs', country: 'IN', description: 'Analyze massive datasets to improve Amazon customer experience. Work on recommendation systems and demand forecasting.' },
  { id: 'int-4', title: 'Product Management Intern', company: 'Flipkart', location: 'Bangalore', duration: '3 months', stipend: '30K/month', applyBy: 'Mar 30, 2026', skills: ['Analytics', 'Communication', 'Problem Solving'], field: 'product', url: 'flipkart.careers', country: 'IN', description: 'Drive product decisions for India\'s largest e-commerce platform. Work with engineering, design, and business teams.' },
  { id: 'int-5', title: 'UX Design Intern', company: 'Swiggy', location: 'Bangalore', duration: '3 months', stipend: '25K/month', applyBy: 'Mar 15, 2026', skills: ['Figma', 'User Research', 'Prototyping'], field: 'design', url: 'swiggy.careers', country: 'IN', description: 'Design intuitive food ordering experiences for millions of users. Conduct user research and create pixel-perfect designs.' },
  { id: 'int-6', title: 'Cybersecurity Intern', company: 'Deloitte India', location: 'Mumbai', duration: '2 months', stipend: '25K/month', applyBy: 'Apr 15, 2026', skills: ['Network Security', 'Python', 'Linux'], field: 'technology', url: 'deloitte.com/careers', country: 'IN', description: 'Assist in security audits and penetration testing for Fortune 500 clients. Learn enterprise security practices.' },
  { id: 'int-7', title: 'Blockchain Developer Intern', company: 'Polygon', location: 'Remote', duration: '3 months', stipend: '40K/month', applyBy: 'Mar 20, 2026', skills: ['Solidity', 'Web3.js', 'Ethereum'], field: 'technology', url: 'polygon.technology/careers', country: 'IN', description: 'Build on Ethereum scaling solutions. Work with cutting-edge blockchain technology at India\'s top Web3 company.' },
  { id: 'int-8', title: 'Financial Analyst Intern', company: 'Goldman Sachs', location: 'Bangalore', duration: '3 months', stipend: '45K/month', applyBy: 'Feb 15, 2026', skills: ['Excel', 'Financial Modeling', 'Python'], field: 'finance', url: 'goldmansachs.com/careers', country: 'IN', description: 'Support trading desks and risk management teams with quantitative analysis. High conversion to full-time offers.' },
  { id: 'int-9', title: 'AI Ethics Research Intern', company: 'NASSCOM', location: 'New Delhi', duration: '2 months', stipend: '15K/month', applyBy: 'May 1, 2026', skills: ['AI/ML', 'Ethics', 'Policy Research'], field: 'ai_ml', url: 'nasscom.in', country: 'IN', description: 'Research AI ethics frameworks for India\'s tech industry. Contribute to policy recommendations and white papers.' },
  { id: 'int-10', title: 'Cloud Engineering Intern', company: 'TCS', location: 'Chennai', duration: '3 months', stipend: '20K/month', applyBy: 'Apr 30, 2026', skills: ['AWS/Azure', 'Docker', 'Kubernetes'], field: 'technology', url: 'tcs.com/careers', country: 'IN', description: 'Work on cloud migration projects for enterprise clients. Gain hands-on experience with AWS and Azure.' },
  { id: 'int-11', title: 'Forensic Science Intern', company: 'CFSL (Govt of India)', location: 'Chandigarh', duration: '2 months', stipend: '10K/month', applyBy: 'May 15, 2026', skills: ['Lab Techniques', 'DNA Analysis', 'Report Writing'], field: 'science', url: 'dfss.gov.in', country: 'IN', description: 'Work alongside government forensic scientists on real cases. Learn DNA profiling, toxicology, and crime scene investigation.' },
  { id: 'int-12', title: 'Renewable Energy Intern', company: 'ReNew Power', location: 'Gurgaon', duration: '3 months', stipend: '20K/month', applyBy: 'Apr 15, 2026', skills: ['Energy Systems', 'Data Analysis', 'AutoCAD'], field: 'engineering', url: 'renewpower.in', country: 'IN', description: 'Work on India\'s largest renewable energy projects. Analyze solar and wind farm performance data.' },
  { id: 'int-13', title: 'Marine Biology Intern', company: 'NIO (CSIR)', location: 'Goa', duration: '2 months', stipend: '12K/month', applyBy: 'May 1, 2026', skills: ['Marine Science', 'Data Collection', 'Diving'], field: 'science', url: 'nio.org', country: 'IN', description: 'Conduct coastal research and coral reef studies. Learn ocean sampling techniques and marine biodiversity assessment.' },
  { id: 'int-14', title: 'Sports Analytics Intern', company: 'Mumbai Indians', location: 'Mumbai', duration: '2 months', stipend: '15K/month', applyBy: 'Mar 1, 2026', skills: ['Python', 'Statistics', 'Cricket Knowledge'], field: 'sports', url: 'mumbaiindians.com', country: 'IN', description: 'Analyze player performance data for IPL team strategy. Build predictive models for match outcomes.' },
  { id: 'int-15', title: 'Robotics Engineering Intern', company: 'GreyOrange', location: 'Gurgaon', duration: '3 months', stipend: '25K/month', applyBy: 'Apr 1, 2026', skills: ['ROS', 'Python', 'C++', 'CAD'], field: 'engineering', url: 'greyorange.com', country: 'IN', description: 'Build warehouse robotics systems used globally. Work on autonomous mobile robots and sorting systems.' },
  { id: 'int-16', title: 'Food Tech Intern', company: 'Zomato', location: 'Gurgaon', duration: '3 months', stipend: '25K/month', applyBy: 'Mar 30, 2026', skills: ['Data Analysis', 'Product Thinking', 'Communication'], field: 'product', url: 'zomato.com/careers', country: 'IN', description: 'Work on hyperpure supply chain and food quality technology. Analyze food delivery data for business insights.' },
  { id: 'int-17', title: 'Music Therapy Intern', company: 'NIMHANS', location: 'Bangalore', duration: '2 months', stipend: '10K/month', applyBy: 'May 15, 2026', skills: ['Music', 'Psychology', 'Patient Care'], field: 'healthcare', url: 'nimhans.ac.in', country: 'IN', description: 'Assist in clinical music therapy sessions for mental health patients. Research the impact of ragas on wellbeing.' },
  { id: 'int-18', title: 'Sustainability Consultant Intern', company: 'EY India', location: 'Mumbai', duration: '3 months', stipend: '30K/month', applyBy: 'Apr 15, 2026', skills: ['ESG Reporting', 'Data Analysis', 'Sustainability'], field: 'consulting', url: 'ey.com/careers', country: 'IN', description: 'Help companies meet ESG compliance requirements. Work on carbon footprint calculations and sustainability strategies.' },
  { id: 'int-19', title: 'Drone Operations Intern', company: 'Asteria Aerospace', location: 'Bangalore', duration: '3 months', stipend: '18K/month', applyBy: 'Apr 30, 2026', skills: ['Drone Piloting', 'GIS', 'Photogrammetry'], field: 'technology', url: 'asteria.co.in', country: 'IN', description: 'Operate industrial drones for mapping and surveillance. Process aerial data for enterprise clients.' },
  { id: 'int-20', title: 'Podcast Production Intern', company: 'Spotify India', location: 'Mumbai', duration: '2 months', stipend: '20K/month', applyBy: 'Mar 15, 2026', skills: ['Audio Editing', 'Script Writing', 'Content Strategy'], field: 'media', url: 'spotifyjobs.com', country: 'IN', description: 'Produce original podcast content for Spotify India. Learn professional audio production and distribution.' },
];

// ===== NEW: Government Course Database =====
export const govtCourseDatabase: GovtCourse[] = [
  { id: 'gc-1', name: 'NPTEL Certification Courses', provider: 'IITs & IISc', duration: '4-12 weeks', cost: 'Free (Exam fee: ₹1000)', eligibility: 'Anyone', certification: 'IIT Certificate', url: 'nptel.ac.in', country: 'IN', description: 'India\'s largest online learning platform with 3000+ courses from IIT professors. Earn certificates recognized by top companies.', skills: ['Engineering', 'Science', 'Management', 'Humanities'] },
  { id: 'gc-2', name: 'SWAYAM Courses', provider: 'MHRD, Govt of India', duration: '4-16 weeks', cost: 'Free', eligibility: 'Anyone', certification: 'UGC/AICTE Credit', url: 'swayam.gov.in', country: 'IN', description: 'Government MOOC platform offering courses from top Indian universities. Credits can be transferred to your degree.', skills: ['All Subjects', 'Credit Courses'] },
  { id: 'gc-3', name: 'PMKVY (Pradhan Mantri Kaushal Vikas Yojana)', provider: 'NSDC, Govt of India', duration: '1-6 months', cost: 'Free', eligibility: 'Unemployed youth (15-45)', certification: 'NSDC Skill Certificate', url: 'pmkvymis.org.in', country: 'IN', description: 'Flagship skill development scheme offering free training in 300+ job roles. Get certified and connected to employers.', skills: ['Manufacturing', 'IT', 'Healthcare', 'Agriculture', 'Construction'] },
  { id: 'gc-4', name: 'Skill India Digital', provider: 'MSDE, Govt of India', duration: '1-12 months', cost: 'Free', eligibility: 'Anyone', certification: 'Skill India Certificate', url: 'skillindiadigital.gov.in', country: 'IN', description: 'Digital platform for skill development with 500+ courses. AI-powered learning paths and industry-recognized certifications.', skills: ['Digital Skills', 'IT', 'Financial Literacy', 'Soft Skills'] },
  { id: 'gc-5', name: 'Digital India Training Programs', provider: 'MeitY, Govt of India', duration: '1-3 months', cost: 'Free', eligibility: 'Anyone', certification: 'NIELIT Certificate', url: 'nielit.gov.in', country: 'IN', description: 'Government IT literacy programs including CCC, O Level, A Level computer courses recognized for government jobs.', skills: ['Computer Basics', 'Programming', 'Web Design', 'Networking'] },
  { id: 'gc-6', name: 'NIOS Vocational Courses', provider: 'National Institute of Open Schooling', duration: '6-12 months', cost: '₹500-2000', eligibility: '14+ years', certification: 'NIOS Vocational Certificate', url: 'nios.ac.in', country: 'IN', description: 'Open schooling vocational courses in trades, agriculture, IT, and services. Flexible learning for school dropouts.', skills: ['IT', 'Agriculture', 'Trades', 'Business'] },
  { id: 'gc-7', name: 'eSkillIndia', provider: 'NSDC', duration: '1-6 months', cost: 'Free', eligibility: 'Anyone', certification: 'NSDC Certificate', url: 'eskillindia.org', country: 'IN', description: 'Free online skill training platform with courses in 50+ sectors. Partners with global content providers.', skills: ['IT', 'Healthcare', 'Retail', 'Logistics', 'Tourism'] },
  { id: 'gc-8', name: 'Startup India Learning Program', provider: 'DPIIT, Govt of India', duration: '4-8 weeks', cost: 'Free', eligibility: 'Aspiring entrepreneurs', certification: 'Startup India Certificate', url: 'startupindia.gov.in', country: 'IN', description: 'Free entrepreneurship development program covering business planning, funding, legal compliance, and scaling.', skills: ['Entrepreneurship', 'Business Planning', 'Funding', 'Marketing'] },
  { id: 'gc-9', name: 'IBM SkillsBuild (India)', provider: 'IBM + MEitY', duration: '2-6 months', cost: 'Free', eligibility: 'Anyone', certification: 'IBM Digital Badge', url: 'skillsbuild.org', country: 'IN', description: 'Free IBM professional training in AI, cloud, cybersecurity, and data science with globally recognized digital badges.', skills: ['AI', 'Cloud', 'Cybersecurity', 'Data Science'] },
  { id: 'gc-10', name: 'AWS Educate (India)', provider: 'Amazon + AICTE', duration: '2-6 months', cost: 'Free', eligibility: 'Students', certification: 'AWS Badge', url: 'awseducate.com', country: 'IN', description: 'Free AWS cloud training for Indian students. Learn cloud computing skills and earn AWS certifications.', skills: ['Cloud Computing', 'AWS', 'DevOps', 'Serverless'] },
];

// ===== NEW: Short Course Database =====
export const shortCourseDatabase: ShortCourse[] = [
  { id: 'sc-1', name: 'Prompt Engineering Masterclass', provider: 'Coursera', duration: '1 week', cost: '₹3,500', skills: ['ChatGPT', 'Prompt Design', 'AI Tools'], mode: 'online', field: 'Technology', url: 'coursera.org', country: 'IN', description: 'Learn to write effective AI prompts for maximum productivity. Master ChatGPT, Claude, and other AI tools.' },
  { id: 'sc-2', name: 'Figma UI Design Bootcamp', provider: 'Udemy', duration: '2 weeks', cost: '₹2,000', skills: ['Figma', 'UI Design', 'Prototyping'], mode: 'online', field: 'Design', url: 'udemy.com', country: 'IN', description: 'Go from zero to creating professional UI designs in Figma. Includes real projects and design systems.' },
  { id: 'sc-3', name: 'Python for Data Science', provider: 'NPTEL', duration: '4 weeks', cost: 'Free (Exam ₹1000)', skills: ['Python', 'Pandas', 'NumPy', 'Visualization'], mode: 'online', field: 'Technology', url: 'nptel.ac.in', country: 'IN', description: 'IIT-certified Python data science course covering NumPy, Pandas, Matplotlib, and Scikit-learn.' },
  { id: 'sc-4', name: 'Digital Marketing Intensive', provider: 'UpGrad', duration: '3 weeks', cost: '₹5,000', skills: ['SEO', 'Google Ads', 'Social Media', 'Analytics'], mode: 'online', field: 'Marketing', url: 'upgrad.com', country: 'IN', description: 'Complete digital marketing course covering SEO, SEM, social media, email marketing, and analytics.' },
  { id: 'sc-5', name: 'AWS Cloud Practitioner Prep', provider: 'A Cloud Guru', duration: '2 weeks', cost: '₹4,000', skills: ['AWS', 'Cloud Concepts', 'Billing', 'Security'], mode: 'online', field: 'Technology', url: 'acloudguru.com', country: 'IN', description: 'Prepare for the AWS Cloud Practitioner certification. Covers cloud concepts, AWS services, and pricing.' },
  { id: 'sc-6', name: 'Excel & Data Analytics Crash Course', provider: 'Scaler', duration: '1 week', cost: '₹2,500', skills: ['Excel', 'Pivot Tables', 'VLOOKUP', 'Charts'], mode: 'online', field: 'Analytics', url: 'scaler.com', country: 'IN', description: 'Master Excel for business analytics. Learn pivot tables, formulas, dashboards, and data visualization.' },
  { id: 'sc-7', name: 'Drone Piloting Certification', provider: 'DGCA Approved Centers', duration: '2 weeks', cost: '₹25,000', skills: ['Drone Flying', 'Air Regulations', 'Navigation'], mode: 'offline', field: 'Technology', url: 'dgca.gov.in', country: 'IN', description: 'Get DGCA-certified drone pilot license. Covers flying skills, air regulations, and drone maintenance.' },
  { id: 'sc-8', name: 'Financial Modeling Workshop', provider: 'WallStreetMojo', duration: '2 weeks', cost: '₹6,000', skills: ['Financial Modeling', 'Valuation', 'Excel', 'DCF'], mode: 'online', field: 'Finance', url: 'wallstreetmojo.com', country: 'IN', description: 'Build financial models from scratch. Learn DCF, LBO, M&A modeling used in investment banking.' },
  { id: 'sc-9', name: 'Cybersecurity Fundamentals', provider: 'Cisco Networking Academy', duration: '3 weeks', cost: 'Free', skills: ['Network Security', 'Cyber Threats', 'Encryption'], mode: 'online', field: 'Technology', url: 'netacad.com', country: 'IN', description: 'Free Cisco course covering cybersecurity principles, threats, and defense mechanisms.' },
  { id: 'sc-10', name: 'React.js Weekend Bootcamp', provider: 'Codecademy', duration: '2 weeks', cost: '₹3,000', skills: ['React', 'JSX', 'Hooks', 'State Management'], mode: 'online', field: 'Technology', url: 'codecademy.com', country: 'IN', description: 'Build interactive web apps with React. Learn components, hooks, routing, and state management.' },
  { id: 'sc-11', name: 'Photography & Photo Editing', provider: 'NIIT', duration: '2 weeks', cost: '₹8,000', skills: ['Photography', 'Lightroom', 'Photoshop', 'Composition'], mode: 'offline', field: 'Creative', url: 'niit.com', country: 'IN', description: 'Learn professional photography and photo editing. Covers camera settings, composition, and post-processing.' },
  { id: 'sc-12', name: 'Communication & Presentation Skills', provider: 'British Council', duration: '1 week', cost: '₹7,000', skills: ['Public Speaking', 'Business Writing', 'Presentations'], mode: 'offline', field: 'Soft Skills', url: 'britishcouncil.in', country: 'IN', description: 'Improve professional communication, public speaking, and presentation skills with British Council trainers.' },
  { id: 'sc-13', name: 'Yoga & Wellness Instructor', provider: 'Morarji Desai National Institute of Yoga', duration: '4 weeks', cost: '₹5,000', skills: ['Yoga', 'Meditation', 'Anatomy', 'Instruction'], mode: 'offline', field: 'Wellness', url: 'mdniy.nic.in', country: 'IN', description: 'Government-certified yoga instructor training. Learn traditional yoga practices and teaching methodology.' },
  { id: 'sc-14', name: 'Content Writing & SEO', provider: 'HubSpot Academy', duration: '1 week', cost: 'Free', skills: ['Content Writing', 'SEO', 'Blogging', 'Copywriting'], mode: 'online', field: 'Marketing', url: 'academy.hubspot.com', country: 'IN', description: 'Free HubSpot certification in content marketing and SEO. Learn to create content that ranks and converts.' },
  { id: 'sc-15', name: 'GST & Tax Filing Practitioner', provider: 'ICAI', duration: '2 weeks', cost: '₹3,000', skills: ['GST', 'Income Tax', 'TDS', 'Filing'], mode: 'online', field: 'Finance', url: 'icai.org', country: 'IN', description: 'ICAI-certified course on GST and tax filing. Become a tax practitioner and help businesses with compliance.' },
  { id: 'sc-16', name: 'Graphic Design with Canva', provider: 'Canva Design School', duration: '1 week', cost: 'Free', skills: ['Canva', 'Graphic Design', 'Branding', 'Social Media'], mode: 'online', field: 'Design', url: 'canva.com/designschool', country: 'IN', description: 'Learn to create professional graphics, presentations, and social media content using Canva.' },
  { id: 'sc-17', name: 'Entrepreneurship Essentials', provider: 'Harvard Business School Online', duration: '3 weeks', cost: '₹12,000', skills: ['Business Model', 'Lean Startup', 'Validation', 'Funding'], mode: 'online', field: 'Business', url: 'online.hbs.edu', country: 'IN', description: 'Harvard Business School course on entrepreneurship fundamentals. Learn to validate ideas and build businesses.' },
  { id: 'sc-18', name: 'Mobile App Development (Flutter)', provider: 'Google Developer Groups', duration: '2 weeks', cost: 'Free', skills: ['Flutter', 'Dart', 'Mobile Development', 'UI'], mode: 'online', field: 'Technology', url: 'developers.google.com/community/gdg', country: 'IN', description: 'Free Google-certified Flutter development course. Build cross-platform mobile apps with one codebase.' },
  { id: 'sc-19', name: 'Stock Market & Trading Basics', provider: 'NSE India', duration: '1 week', cost: '₹1,500', skills: ['Stock Trading', 'Technical Analysis', 'Risk Management'], mode: 'online', field: 'Finance', url: 'nseindia.com', country: 'IN', description: 'NSE-certified course on stock market basics, technical analysis, and trading strategies for beginners.' },
  { id: 'sc-20', name: 'Video Editing with DaVinci Resolve', provider: 'YouTube Creators Academy', duration: '2 weeks', cost: 'Free', skills: ['Video Editing', 'DaVinci Resolve', 'Color Grading', 'Effects'], mode: 'online', field: 'Creative', url: 'youtube.com/creators', country: 'IN', description: 'Learn professional video editing using free DaVinci Resolve software. Create YouTube-ready content.' },
];

// Helper: Get institutions for a course
export function getInstitutionsForCourse(courseId: string, countryCode?: string): Institution[] {
  return institutionDatabase.filter(inst => {
    const hasCourse = inst.courses.includes(courseId);
    if (countryCode) {
      return hasCourse && inst.location.country === countryCode;
    }
    return hasCourse;
  }).sort((a, b) => (a.ranking.national || 999) - (b.ranking.national || 999));
}

// Helper: Get courses for a country
export function getCoursesForCountry(countryCode: string): UniqueCourse[] {
  return uniqueCoursesDatabase.filter(c => c.countries.includes(countryCode));
}

// Helper: Get internships for a country
export function getInternshipsForCountry(countryCode: string): Internship[] {
  return internshipDatabase.filter(i => i.country === countryCode);
}

// Helper: Get govt courses for a country
export function getGovtCoursesForCountry(countryCode: string): GovtCourse[] {
  return govtCourseDatabase.filter(g => g.country === countryCode);
}

// Helper: Get short courses for a country
export function getShortCoursesForCountry(countryCode: string): ShortCourse[] {
  return shortCourseDatabase.filter(s => s.country === countryCode);
}
